spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:admin123}
    username: ${POSTGRES_USER:postgres}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:rinha_db}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect